all: numbers typenum strings
	@echo "Compilo tutto!"
	
numbers:
	g++ lezione_1_numbers.cpp -o numbers

typenum:
	g++ lezione_1_typeNumbers.cpp -o typeNum

strings:
	g++ lezione_1_strings.cpp -o strings
